import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const colors = {
    blue: '#0041C4',
    lightGrey: '#E9ECF1',
    grey: '#ABABAB',
    black: '#000000',
}

const styles = StyleSheet.create({

    textcenter: { textAlign: 'center' },
    textleft: { textAlign: 'left' },
    textright: { textAlign: 'right' },

    j_center: { justifyContent: 'center' },
    j_start: { justifyContent: 'flex-start' },
    j_end: { justifyContent: 'flex-end' },
    j_between: { justifyContent: 'space-between' },

    a_center: { alignItems: 'center' },
    a_start: { alignItems: 'flex-start' },
    a_end: { alignItems: 'flex-end' },

    m1: { margin: hp('1%') },
    m2: { margin: hp('2%') },
    m3: { margin: hp('3%') },
    m4: { margin: hp('4%') },
    m5: { margin: hp('5%') },
    m6: { margin: hp('6%') },
    m7: { margin: hp('7%') },
    m8: { margin: hp('8%') },
    m9: { margin: hp('9%') },
    m10: { margin: hp('10%') },
    m12: { margin: hp('12%') },
    m14: { margin: hp('14%') },
    m16: { margin: hp('16%') },
    m18: { margin: hp('18%') },
    m20: { margin: hp('20%') },
    m25: { margin: hp('25%') },
    m30: { margin: hp('30%') },
    m35: { margin: hp('35%') },
    m40: { margin: hp('40%') },
    m45: { margin: hp('45%') },
    m50: { margin: hp('50%') },

    ml1: { marginLeft: hp('1%') },
    ml2: { marginLeft: hp('2%') },
    ml3: { marginLeft: hp('3%') },
    ml4: { marginLeft: hp('4%') },
    ml5: { marginLeft: hp('5%') },
    ml6: { marginLeft: hp('6%') },
    ml7: { marginLeft: hp('7%') },
    ml8: { marginLeft: hp('8%') },
    ml9: { marginLeft: hp('9%') },
    ml10: { marginLeft: hp('10%') },
    ml12: { marginLeft: hp('12%') },
    ml14: { marginLeft: hp('14%') },
    ml16: { marginLeft: hp('16%') },
    ml18: { marginLeft: hp('18%') },
    ml20: { marginLeft: hp('20%') },
    ml25: { marginLeft: hp('25%') },
    ml30: { marginLeft: hp('30%') },
    ml35: { marginLeft: hp('35%') },
    ml40: { marginLeft: hp('40%') },
    ml45: { marginLeft: hp('45%') },
    ml50: { marginLeft: hp('50%') },

    mr1: { marginRight: hp('1%') },
    mr2: { marginRight: hp('2%') },
    mr3: { marginRight: hp('3%') },
    mr4: { marginRight: hp('4%') },
    mr5: { marginRight: hp('5%') },
    mr6: { marginRight: hp('6%') },
    mr7: { marginRight: hp('7%') },
    mr8: { marginRight: hp('8%') },
    mr9: { marginRight: hp('9%') },
    mr10: { marginRight: hp('10%') },
    mr12: { marginRight: hp('12%') },
    mr14: { marginRight: hp('14%') },
    mr16: { marginRight: hp('16%') },
    mr18: { marginRight: hp('18%') },
    mr20: { marginRight: hp('20%') },
    mr25: { marginRight: hp('25%') },
    mr30: { marginRight: hp('30%') },
    mr35: { marginRight: hp('35%') },
    mr40: { marginRight: hp('40%') },
    mr45: { marginRight: hp('45%') },
    mr50: { marginRight: hp('50%') },

    mt1: { marginTop: hp('1%') },
    mt2: { marginTop: hp('2%') },
    mt3: { marginTop: hp('3%') },
    mt4: { marginTop: hp('4%') },
    mt5: { marginTop: hp('5%') },
    mt6: { marginTop: hp('6%') },
    mt7: { marginTop: hp('7%') },
    mt8: { marginTop: hp('8%') },
    mt9: { marginTop: hp('9%') },
    mt10: { marginTop: hp('10%') },
    mt12: { marginTop: hp('12%') },
    mt14: { marginTop: hp('14%') },
    mt16: { marginTop: hp('16%') },
    mt18: { marginTop: hp('18%') },
    mt20: { marginTop: hp('20%') },
    mt25: { marginTop: hp('25%') },
    mt30: { marginTop: hp('30%') },
    mt35: { marginTop: hp('35%') },
    mt40: { marginTop: hp('40%') },
    mt45: { marginTop: hp('45%') },
    mt50: { marginTop: hp('50%') },

    mb1: { marginBottom: hp('1%') },
    mb2: { marginBottom: hp('2%') },
    mb3: { marginBottom: hp('3%') },
    mb4: { marginBottom: hp('4%') },
    mb5: { marginBottom: hp('5%') },
    mb6: { marginBottom: hp('6%') },
    mb7: { marginBottom: hp('7%') },
    mb8: { marginBottom: hp('8%') },
    mb9: { marginBottom: hp('9%') },
    mb10: { marginBottom: hp('10%') },
    mb12: { marginBottom: hp('12%') },
    mb14: { marginBottom: hp('14%') },
    mb16: { marginBottom: hp('16%') },
    mb18: { marginBottom: hp('18%') },
    mb20: { marginBottom: hp('20%') },
    mb25: { marginBottom: hp('25%') },
    mb30: { marginBottom: hp('30%') },
    mb35: { marginBottom: hp('35%') },
    mb40: { marginBottom: hp('40%') },
    mb45: { marginBottom: hp('45%') },
    mb50: { marginBottom: hp('50%') },

    p1: { padding: hp('1%') },
    p2: { padding: hp('2%') },
    p3: { padding: hp('3%') },
    p4: { padding: hp('4%') },
    p5: { padding: hp('5%') },
    p6: { padding: hp('6%') },
    p7: { padding: hp('7%') },
    p8: { padding: hp('8%') },
    p9: { padding: hp('9%') },
    p10: { padding: hp('10%') },
    p12: { padding: hp('12%') },
    p14: { padding: hp('14%') },
    p16: { padding: hp('16%') },
    p18: { padding: hp('18%') },
    p20: { padding: hp('20%') },
    p25: { padding: hp('25%') },
    p30: { padding: hp('30%') },
    p35: { padding: hp('35%') },
    p40: { padding: hp('40%') },
    p45: { padding: hp('45%') },
    p50: { padding: hp('50%') },

    pl1: { paddingLeft: hp('1%') },
    pl2: { paddingLeft: hp('2%') },
    pl3: { paddingLeft: hp('3%') },
    pl4: { paddingLeft: hp('4%') },
    pl5: { paddingLeft: hp('5%') },
    pl6: { paddingLeft: hp('6%') },
    pl7: { paddingLeft: hp('7%') },
    pl8: { paddingLeft: hp('8%') },
    pl9: { paddingLeft: hp('9%') },
    pl10: { paddingLeft: hp('10%') },
    pl12: { paddingLeft: hp('12%') },
    pl14: { paddingLeft: hp('14%') },
    pl16: { paddingLeft: hp('16%') },
    pl18: { paddingLeft: hp('18%') },
    pl20: { paddingLeft: hp('20%') },
    pl25: { paddingLeft: hp('25%') },
    pl30: { paddingLeft: hp('30%') },
    pl35: { paddingLeft: hp('35%') },
    pl40: { paddingLeft: hp('40%') },
    pl45: { paddingLeft: hp('45%') },
    pl50: { paddingLeft: hp('50%') },

    pr1: { paddingRight: hp('1%') },
    pr2: { paddingRight: hp('2%') },
    pr3: { paddingRight: hp('3%') },
    pr4: { paddingRight: hp('4%') },
    pr5: { paddingRight: hp('5%') },
    pr6: { paddingRight: hp('6%') },
    pr7: { paddingRight: hp('7%') },
    pr8: { paddingRight: hp('8%') },
    pr9: { paddingRight: hp('9%') },
    pr10: { paddingRight: hp('10%') },
    pr12: { paddingRight: hp('12%') },
    pr14: { paddingRight: hp('14%') },
    pr16: { paddingRight: hp('16%') },
    pr18: { paddingRight: hp('18%') },
    pr20: { paddingRight: hp('20%') },
    pr25: { paddingRight: hp('25%') },
    pr30: { paddingRight: hp('30%') },
    pr35: { paddingRight: hp('35%') },
    pr40: { paddingRight: hp('40%') },
    pr45: { paddingRight: hp('45%') },
    pr50: { paddingRight: hp('50%') },

    pt1: { paddingTop: hp('1%') },
    pt2: { paddingTop: hp('2%') },
    pt3: { paddingTop: hp('3%') },
    pt4: { paddingTop: hp('4%') },
    pt5: { paddingTop: hp('5%') },
    pt6: { paddingTop: hp('6%') },
    pt7: { paddingTop: hp('7%') },
    pt8: { paddingTop: hp('8%') },
    pt9: { paddingTop: hp('9%') },
    pt10: { paddingTop: hp('10%') },
    pt12: { paddingTop: hp('12%') },
    pt14: { paddingTop: hp('14%') },
    pt16: { paddingTop: hp('16%') },
    pt18: { paddingTop: hp('18%') },
    pt20: { paddingTop: hp('20%') },
    pt25: { paddingTop: hp('25%') },
    pt30: { paddingTop: hp('30%') },
    pt35: { paddingTop: hp('35%') },
    pt40: { paddingTop: hp('40%') },
    pt45: { paddingTop: hp('45%') },
    pt50: { paddingTop: hp('50%') },

    pb1: { paddingBottom: hp('1%') },
    pb2: { paddingBottom: hp('2%') },
    pb3: { paddingBottom: hp('3%') },
    pb4: { paddingBottom: hp('4%') },
    pb5: { paddingBottom: hp('5%') },
    pb6: { paddingBottom: hp('6%') },
    pb7: { paddingBottom: hp('7%') },
    pb8: { paddingBottom: hp('8%') },
    pb9: { paddingBottom: hp('9%') },
    pb10: { paddingBottom: hp('10%') },
    pb12: { paddingBottom: hp('12%') },
    pb14: { paddingBottom: hp('14%') },
    pb16: { paddingBottom: hp('16%') },
    pb18: { paddingBottom: hp('18%') },
    pb20: { paddingBottom: hp('20%') },
    pb25: { paddingBottom: hp('25%') },
    pb30: { paddingBottom: hp('30%') },
    pb35: { paddingBottom: hp('35%') },
    pb40: { paddingBottom: hp('40%') },
    pb45: { paddingBottom: hp('45%') },
    pb50: { paddingBottom: hp('50%') },

    w5: { width: '5%' },
    w10: { width: '10%' },
    w15: { width: '15%' },
    w20: { width: '5%' },
    w25: { width: '25%' },
    w30: { width: '5%' },
    w35: { width: '35%' },
    w40: { width: '5%' },
    w45: { width: '45%' },
    w50: { width: '5%' },
    w55: { width: '55%' },
    w60: { width: '5%' },
    w65: { width: '65%' },
    w70: { width: '5%' },
    w75: { width: '75%' },
    w80: { width: '5%' },
    w85: { width: '85%' },
    w90: { width: '5%' },
    w95: { width: '95%' },
    w100: { width: '100%' },
    wauto: { width: 'auto' },

    h5: { height: '5%' },
    h10: { height: '10%' },
    h15: { height: '15%' },
    h20: { height: '5%' },
    h25: { height: '25%' },
    h30: { height: '5%' },
    h35: { height: '35%' },
    h40: { height: '5%' },
    h45: { height: '45%' },
    h50: { height: '5%' },
    h55: { height: '55%' },
    h60: { height: '5%' },
    h65: { height: '65%' },
    h70: { height: '5%' },
    h75: { height: '75%' },
    h80: { height: '5%' },
    h85: { height: '85%' },
    h90: { height: '5%' },
    h95: { height: '95%' },
    h100: { height: '100%' },
    hauto: { height: 'auto' },

    top0: { top: 0 },
    left0: { left: 0 },
    right0: { right: 0 },
    bottom0: { bottom: 0 },

    flex: { display: 'flex' },
    hide: { display: 'none' },
    row: { display: 'flex', flexDirection: 'row' },
    col: { display: 'flex', flexDirection: 'column' },

    wrap: { flexWrap: 'wrap' },

    flex1: { flex: 1 },
    flex2: { flex: 2 },
    flex3: { flex: 3 },
    flex4: { flex: 4 },
    flex5: { flex: 5 },
    flex6: { flex: 6 },
    flex7: { flex: 7 },
    flex8: { flex: 8 },
    flex9: { flex: 9 },
    flex10: { flex: 10 },
    flex11: { flex: 11 },

    relative: { position: 'relative' },
    absolute: { position: 'absolute' },

    br1: { borderRadius: wp('0.2%') },
    br2: { borderRadius: wp('0.4%') },
    br3: { borderRadius: wp('0.6%') },
    br4: { borderRadius: wp('0.8%') },
    br5: { borderRadius: wp('1%') },
    br6: { borderRadius: wp('1.2%') },
    br7: { borderRadius: wp('1.4%') },
    br8: { borderRadius: wp('1.6%') },
    br9: { borderRadius: wp('1.8%') },
    br10: { borderRadius: wp('2%') },
    br11: { borderRadius: wp('2.2%') },
    br12: { borderRadius: wp('2.4%') },
    br13: { borderRadius: wp('2.6%') },
    br14: { borderRadius: wp('2.8%') },
    br15: { borderRadius: wp('3%') },
    br16: { borderRadius: wp('3.2%') },
    br17: { borderRadius: wp('3.4%') },
    br18: { borderRadius: wp('3.6%') },
    br19: { borderRadius: wp('3.8%') },
    br20: { borderRadius: wp('4%') },

    bw1: { borderWidth: 1 },
    bw2: { borderWidth: 2 },
    bw3: { borderWidth: 3 },
    bw4: { borderWidth: 4 },
    bw5: { borderWidth: 5 },

    solid: { borderStyle: 'solid' },
    dotted: { borderStyle: 'dotted' },
    dashed: { borderStyle: 'dashed' },
})

export default styles;